### ISSUE TITLE
Upcoming Development filemover

### ISSUE THREAD

**Issue by codeperfectplus** [codeperfectplus/movens#7]
## Upcoming development (November)

1. Create PyPI Package to manage files in one click with CLI.

Proposed CLI Commands Example:

```
filemover.py --video # if only want to rearrange videos
filemover.py --audio # if only want to rearrange audio
filemover.py --other # rearrange other type extension
filemover.py --all # rearrange everything.
filemover.py --all -d <directory>
```

By default, it will run in the download directory, as you know download folder is very messy for all of us. But the directory can be changed by CLI input.

Initial alpha version:- 0.0.1

2. Create proper sphinx documentation similar to other projects maintained by Py-contributors.

Reference:- https://cybel.readthedocs.io/

`Suggestions are welcome`

**Comment by ExpressHermes** [comment]
Couple of improvements that I think should be made to the package:

-  Most of the functions are duplicated in `filemover.py` and `filemovergui.py`. I think those should be extracted in a single file and imported from there to both the modules.
- Current flow creates all the folders, even if these are no files to put in them. I think, the directories should be created only for the file types that are present.


I am working on these and will create a PR once done

**Comment by codeperfectplus** [comment]
for the duplicate functions, that was intentional.
So users can download one file locally. if they want CLI/GUI. They have to copy only one file. 
as we are creating a CLI version of the tool now, GUI will be moved/deleted to experimental/Other.

Agreed with 2nd point.

**Comment by ExpressHermes** [comment]
Got it, will create PR for the second point
